name: Go CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Generate code
        run: go generate ./...
      - name: Ensure no diff
        run: git diff --exit-code
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: API tests
        run: pytest -vv tests

